// Build step: downscales ../assets/logo.png and writes it into js/logoData.js as
// a data URI. The app must run from file://, where fetch() of a sibling image is
// blocked by CORS and a canvas drawn from a local <img> is tainted - so neither
// jsPDF nor ExcelJS could read the pixels at runtime. Inlining sidesteps both.
// Run: npm run logo
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SIZE = 256; // 0.9in in the PDF and 90px in Excel; 256 is retina-sharp for both.

const source = PNG.sync.read(readFileSync(resolve(root, "assets/logo.png")));
const target = new PNG({ width: SIZE, height: SIZE });

// Box filter: average every source pixel that falls inside the target pixel,
// weighting colour by alpha so transparent edges do not bleed dark halos.
const scaleX = source.width / SIZE;
const scaleY = source.height / SIZE;

for (let y = 0; y < SIZE; y += 1) {
  for (let x = 0; x < SIZE; x += 1) {
    const x0 = Math.floor(x * scaleX);
    const x1 = Math.max(x0 + 1, Math.floor((x + 1) * scaleX));
    const y0 = Math.floor(y * scaleY);
    const y1 = Math.max(y0 + 1, Math.floor((y + 1) * scaleY));

    let r = 0;
    let g = 0;
    let b = 0;
    let a = 0;
    let count = 0;

    for (let sy = y0; sy < y1; sy += 1) {
      for (let sx = x0; sx < x1; sx += 1) {
        const index = (source.width * sy + sx) << 2;
        const alpha = source.data[index + 3] / 255;
        r += source.data[index] * alpha;
        g += source.data[index + 1] * alpha;
        b += source.data[index + 2] * alpha;
        a += alpha;
        count += 1;
      }
    }

    const out = (SIZE * y + x) << 2;
    const alphaMean = a / count;
    target.data[out] = alphaMean ? Math.round(r / count / alphaMean) : 0;
    target.data[out + 1] = alphaMean ? Math.round(g / count / alphaMean) : 0;
    target.data[out + 2] = alphaMean ? Math.round(b / count / alphaMean) : 0;
    target.data[out + 3] = Math.round(alphaMean * 255);
  }
}

const png = PNG.sync.write(target, { deflateLevel: 9 });
const base64 = png.toString("base64");

writeFileSync(
  resolve(root, "js/logoData.js"),
  `// GENERATED by scripts/embedLogo.mjs - do not edit by hand.
// assets/logo.png downscaled to ${SIZE}x${SIZE} and inlined as a data URI, because a
// file:// page can neither fetch() a local image nor read one back out of a canvas.
(function () {
  const SLV = (globalThis.SLV = globalThis.SLV || {});
  SLV.LOGO_PNG_DATA_URI =
    "data:image/png;base64,${base64}";
})();
`,
  "utf8"
);

// The same 256px PNG doubles as the favicon: it is what Chrome stamps on the
// shortcut the client creates from the page.
writeFileSync(resolve(root, "assets/icon.png"), png);

console.log(`js/logoData.js and assets/icon.png written - ${SIZE}x${SIZE}, ${(base64.length / 1024).toFixed(0)} KB of base64`);
